### ISSUE TITLE
ModuleNotFounder:No module named 'cpp_wrappers.cpp_neighbors.radius_neighbors'

### ISSUE THREAD

**Issue by xsf777** [JohannesErnst/WeaSAL#3]
![image](https://user-images.githubusercontent.com/89497789/179179827-1b88701e-903e-42cb-9616-94dd97c9579b.png)

**Comment by JohannesErnst** [comment]
Sorry the repo is still work in progress and therfore I didn't add proper installation instructions yet. 

This error is most likely because you first have to compile the wrappers and install other dependencies in order for the KPConv backbone to run. Please see https://github.com/HuguesTHOMAS/KPConv-PyTorch/blob/master/INSTALL.md

I will add installation instructions in addition to my conda environment once the project is finished.

**Comment by xsf777** [comment]
thanks
